micronaut:
  application:
    name: open-event
  server:
    port: 8080
    thread-selection: AUTO
    netty:
      access-logger:
        enabled: true
        exclusions:
          - /health
          - /prometheus
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ""
        enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /health/**
        access:
          - isAnonymous()
      - pattern: /api/**
        access:
          - isAuthenticated()
      - pattern: /static/**
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAnonymous()


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: NONE
    dialect: POSTGRES
    schema: open_event

netty:
  default:
    allocator:
      max-order: 3

flyway:
  datasources:
    default:
      enabled: true
      default-schema: open_event
      create-schemas: true
      schemas: open_event
      clean-schema: false

tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1
  exclusions:
    - /health
    - /env/.*
