package de.sambalmueslie.openevent.infrastructure.audit.api

enum class AuditAction {
    CREATE,
    UPDATE,
    DELETE,

    EVENT_CANCELLED,
    EVENT_STATUS_CHANGED,
    EVENT_PUBLISH_CHANGED,
    EVENT_PUBLISHED_CHANGED,
    EVENT_SHARED_CHANGED,
    EVENT_FEATURED_CHANGED,
    EVENT_BOOKMARK_ADDED,
    EVENT_BOOKMARK_REMOVED,
    EVENT_TITLE_CHANGED,
    EVENT_SHORT_TEXT_CHANGED,
    EVENT_LONG_TEXT_CHANGED,
    EVENT_TAGS_CHANGED,
    EVENT_TEXT_CHANGED,
    EVENT_CATEGORIES_CHANGED,
    EVENT_AUDIENCES_CHANGED,
    EVENT_ANNOUNCEMENT_ADDED,
    EVENT_ANNOUNCEMENT_REMOVED,

    REGISTRATION_PARTICIPANT_ADDED,
    REGISTRATION_PARTICIPANT_CHANGED,
    REGISTRATION_PARTICIPANT_REMOVED,

    ADDRESS_SET_DEFAULT
}
